# Grype reports alerts that we decide to ignore with reasons.
# 
# NAME               INSTALLED   FIXED IN  TYPE    VULNERABILITY        SEVERITY  EPSS         RISK                 
# setuptools         82.0.1      83.0.0    python  GHSA-h35f-9h28-mq5c  Medium    0.4% (33rd)  0.2
# 
# setuptools: Severity medium, concerning essentially build systems that this Docker is not.
#             Will be fixed by next version of Alpine.
ignore:
  - vulnerability: GHSA-h35f-9h28-mq5c
show-suppressed: true
