trigger:
  branches:
    exclude:
      - "*"
  tags:
    include:
      - "4.*"

pr: none

stages:
  - stage: build_test
    jobs:
      - template: templates/integration-jobs.yml
  - stage: release
    jobs:
      - template: templates/release-jobs.yml
