name: release

on:
  push:
    tags: ["4.*"]

jobs:
  main:
    uses: ./.github/workflows/main.yml
  docker:
    needs: main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build, tag and push to GHCR
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/mjechow/docker-backuppc:${{ github.ref_name }}
            ghcr.io/mjechow/docker-backuppc:4
            ghcr.io/mjechow/docker-backuppc:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  github:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Get changelog
        run: |
          python utils/extract_changelog.py "${{ github.ref_name }}" > extracted_changelog.md
      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          name: Docker BackupPC ${{ github.ref_name }}
          body_path: extracted_changelog.md
